### ISSUE TITLE
Add more stocks to the project

### ISSUE THREAD

**Issue by ad-dan** [ad-dan/finance#1]
In the `app.js` there's an property called `stocks` on the main app. Feel free to add more stocks whether they be real or completely imaginary with made up symbols and prices. Make sure to follow the format `ticker: [name, price]`.

**Comment by drex44** [comment]
hi, I want to take this on!

**Comment by ad-dan** [comment]
sure man go ahead.

**Comment by manolingam** [comment]
hello, I want to take this.

**Comment by manolingam** [comment]
Have submitted a pull request.
